{
    "name": "University",
    "version": "18.0.0.1",
    "author": "varoESP",
    "website": "https://github.com/VaroESP",
    "category": "Education",
    "depends": ["base", "mail", "website", "web"],
    "data": [
        "security/ir.model.access.csv",
        "reports/university_report_student_views.xml",
        "reports/university_report_student_pdf_views.xml",
        "wizard/student_wizard_mail.xml",
        "views/university_university_views.xml",
        "views/university_department_views.xml",
        "views/university_teacher_views.xml",
        "views/university_student_views.xml",
        "views/university_subject_views.xml",
        "views/university_tuition_views.xml",
        "views/university_grade_views.xml",
        "views/university_student_mail_template.xml",
        "views/university_portal_views.xml",
        "views/university_menus.xml",
        "views/university_website_views.xml",
        "views/university_website_menu.xml",
    ],
    "demo": [
        "demo/university_demo_data.xml",
    ],
    "qweb": [],
    "assets": {
        "web.assets_backend": [
            "university/static/src/toaster_button/*",
        ],
    },
    "test": [
        "tests/test_department.py",
        "tests/test_grade.py",
        "tests/test_student.py",
        "tests/test_subject.py",
        "tests/test_teacher.py",
        "tests/test_tuition.py",
        "tests/test_university.py",
    ],
    "installable": True,
    "application": True,
    "languages": ["es"],
    "license": "LGPL-3",
}
